/**
 * Regenerates skill-inventory.json from SKILL.md frontmatter + manifest.json.
 * The inventory is the canonical catalog seed source consumed by build-seed.ts.
 */
import { loadAllSkills, REPO_ROOT, join, readFileSync } from "./lib.js";
import { writeFileSync } from "node:fs";

const manifest = JSON.parse(readFileSync(join(REPO_ROOT, "manifest.json"), "utf8"));

const skills = loadAllSkills().map((s) => ({
  id: s.id,
  name: String(s.frontmatter.name ?? s.id),
  description: String(s.frontmatter.description ?? "").trim(),
  category: (s.frontmatter.category as string) ?? "uncategorized",
  risk_level: (s.frontmatter.risk_level as string) ?? "medium",
  requires_current_rules: s.frontmatter.requires_current_rules === true,
}));

// Order skills to match manifest.skill_ids where possible.
const order: string[] = manifest.skill_ids ?? [];
skills.sort((a, b) => {
  const ai = order.indexOf(a.id);
  const bi = order.indexOf(b.id);
  if (ai === -1 && bi === -1) return a.id.localeCompare(b.id);
  if (ai === -1) return 1;
  if (bi === -1) return -1;
  return ai - bi;
});

const inventory = {
  _generated: "Generated by scripts/build-inventory.ts from SKILL.md frontmatter. Do not edit by hand.",
  pack: {
    id: manifest.id,
    display_name: manifest.display_name,
    neutral_display_name: manifest.neutral_display_name,
    brand_authorized: manifest.brand_authorized === true,
  },
  skills,
};

const out = join(REPO_ROOT, "skill-inventory.json");
writeFileSync(out, JSON.stringify(inventory, null, 2) + "\n", "utf8");
console.log(`✓ build:inventory: wrote ${skills.length} skills to skill-inventory.json`);

// Sanity: every manifest id present
const ids = new Set(skills.map((s) => s.id));
const missing = order.filter((id) => !ids.has(id));
if (missing.length) {
  console.error(`✗ build:inventory: manifest ids without a skill folder: ${missing.join(", ")}`);
  process.exit(1);
}
