/**
 * Regenerates seed/seed.sql from skill-inventory.json + manifest.json + each
 * SKILL.md body. Emits an idempotent upsert into the Skill Me skills/packs tables.
 *
 * The target schema was CONFIRMED against the live Skill Me Supabase project on
 * 2026-06-21 (skills.slug unique key + skill_content body; packs.slug unique key;
 * pack_skills association). If you cannot confirm the schema, run with --template
 * to emit a clearly-marked placeholder instead of guessing columns.
 */
import { loadSkill, REPO_ROOT, join, readFileSync } from "./lib.js";
import { writeFileSync } from "node:fs";

const TEMPLATE_MODE = process.argv.includes("--template");

const manifest = JSON.parse(readFileSync(join(REPO_ROOT, "manifest.json"), "utf8"));
const inventory = JSON.parse(readFileSync(join(REPO_ROOT, "skill-inventory.json"), "utf8"));

const NOTICE =
  "This independent skill repository is not official, endorsed, sponsored, approved, or certified by CrossFit, LLC or its affiliates.";
const AUTHOR = manifest.author ?? "crossfit-claude-skills contributors";
const PACK_SLUG: string = manifest.id;
// Brand not authorized -> seed under the neutral display name.
const PACK_NAME: string = manifest.brand_authorized
  ? manifest.display_name
  : manifest.neutral_display_name;

const TAG = "$cfseed$";
function dq(s: string): string {
  // dollar-quote; guard against the (extremely unlikely) tag appearing in content.
  if (s.includes(TAG)) {
    const alt = "$cfseed_x$";
    return `${alt}${s}${alt}`;
  }
  return `${TAG}${s}${TAG}`;
}

/** Single-quoted SQL string literal for short, simple slug values. */
function sqlTag(s: string): string {
  return `'${String(s).replace(/'/g, "''")}'`;
}

function templateHeader(): string {
  return `-- ============================================================================
-- seed.sql — TEMPLATE MODE (schema NOT confirmed)
-- ============================================================================
-- TODO: Confirm the live Skill Me 'skills' and 'packs' column definitions before
-- applying. Replace the placeholder column lists below. Do NOT apply this file
-- as-is. Regenerate without --template once the schema is confirmed.
--
-- Expected (from prior confirmation, verify before use):
--   skills(slug UNIQUE, name, description, category, subcategory, source_url,
--          author, skill_content, tags, free, verified, featured)
--   packs(slug UNIQUE, name, tagline, description, author, author_url, category,
--         tags, repo_url, free, verified)
--   pack_skills(pack_id, skill_id, position)
-- ============================================================================

-- <<PLACEHOLDER: pack upsert>>
-- insert into packs (<<COLUMNS>>) values (<<VALUES>>) on conflict (slug) do update set ...;

-- <<PLACEHOLDER: per-skill upsert>>
-- insert into skills (<<COLUMNS>>) values (<<VALUES>>) on conflict (slug) do update set ...;

-- <<PLACEHOLDER: pack_skills association>>
`;
}

if (TEMPLATE_MODE) {
  const out = join(REPO_ROOT, "seed", "seed.sql");
  writeFileSync(out, templateHeader(), "utf8");
  console.log("✓ build:seed: wrote TEMPLATE seed/seed.sql (schema unconfirmed mode).");
  process.exit(0);
}

const lines: string[] = [];
lines.push("-- ============================================================================");
lines.push("-- seed.sql — generated by scripts/build-seed.ts. Do not edit by hand.");
lines.push("-- Idempotent upsert into the Skill Me catalog (skills, packs, pack_skills).");
lines.push("-- Schema confirmed against the live Skill Me Supabase project on 2026-06-21.");
lines.push(`-- ${NOTICE}`);
lines.push("-- ============================================================================");
lines.push("");
lines.push("begin;");
lines.push("");

// ---- pack upsert ----
const packDescription = `${manifest.purpose}\n\n${manifest.notes ?? NOTICE}`;
const packTagline =
  manifest.tagline ??
  "Mixed-modal functional fitness coaching: programming, scaling, classes, competition & credentials.";
const AUTHOR_URL = manifest.author_url ?? null;
const REPO_URL = manifest.repo_url ?? null;
lines.push("-- Pack — CrossFit® name/badges used under the maintainer's affiliate/trainer license.");
lines.push(
  `insert into packs (slug, name, tagline, description, author, author_url, category, tags, repo_url, free, verified)
values (
  ${dq(PACK_SLUG)},
  ${dq(PACK_NAME)},
  ${dq(packTagline)},
  ${dq(packDescription)},
  ${dq(AUTHOR)},
  ${AUTHOR_URL ? dq(AUTHOR_URL) : "null"},
  ${dq("mixed")},
  array['crossfit','functional-fitness','coaching','programming','competition']::text[],
  ${REPO_URL ? dq(REPO_URL) : "null"},
  true,
  false
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  author = excluded.author,
  author_url = excluded.author_url,
  category = excluded.category,
  tags = excluded.tags,
  repo_url = excluded.repo_url,
  updated_at = now();`
);
lines.push("");

// ---- skills upsert ----
lines.push("-- Skills (catalog category 'personal'; internal taxonomy kept in subcategory).");
for (const inv of inventory.skills as Array<any>) {
  const skill = loadSkill(inv.id);
  const body = skill.body.trim();
  lines.push(
    `insert into skills (slug, name, description, category, subcategory, author, skill_content, tags, free, verified)
values (
  ${dq(inv.id)},
  ${dq(inv.name)},
  ${dq(inv.description)},
  ${dq("personal")},
  ${dq(inv.category)},
  ${dq(AUTHOR)},
  ${dq(body)},
  array['crossfit','functional-fitness',${sqlTag(inv.category)}]::text[],
  true,
  false
)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  subcategory = excluded.subcategory,
  author = excluded.author,
  skill_content = excluded.skill_content,
  tags = excluded.tags,
  updated_at = now();`
  );
  lines.push("");
}

// ---- pack_skills association (idempotent: clear then re-insert) ----
lines.push("-- Associate every skill with the pack (idempotent).");
lines.push(
  `delete from pack_skills where pack_id = (select id from packs where slug = ${dq(PACK_SLUG)});`
);
const valueRows = (inventory.skills as Array<any>)
  .map((inv, i) => `  (${dq(inv.id)}, ${i})`)
  .join(",\n");
lines.push(
  `insert into pack_skills (pack_id, skill_id, position)
select p.id, s.id, v.position
from (values
${valueRows}
) as v(slug, position)
join packs p on p.slug = ${dq(PACK_SLUG)}
join skills s on s.slug = v.slug;`
);
lines.push("");
lines.push("commit;");
lines.push("");

const out = join(REPO_ROOT, "seed", "seed.sql");
writeFileSync(out, lines.join("\n"), "utf8");
console.log(`✓ build:seed: wrote seed/seed.sql (1 pack, ${inventory.skills.length} skills).`);
